dist: xenial
language: go
sudo: true

go:
  - "tip"
  - "1.13.x"
  - "1.12.x"

jobs:
  fast_finish: true
  include:
    - name: "generate"
      before_install: skip
      install:
      - mkdir ../protoc
      - |
        echo "Installing Protobuf compiler"
        (
          set -e
          cd ../protoc
          wget "https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
          unzip "protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
        )
      - export PATH="$(pwd)/../protoc/bin:$PATH"
      - go install github.com/golang/protobuf/proto
      - go install github.com/golang/protobuf/protoc-gen-go
      before_script: skip
      script:
      - |
        cd ./proto
        protoc --go_out=. ./dropbox/proto/kglb/*.proto
        protoc --go_out=. ./dropbox/proto/kglb/healthchecker/*.proto
    - name: "test"
      before_install: skip
      install: skip
      script: go test ./...
    - name: "coverage"
      before_install: skip
      install: skip
      before_script: skip
      script: go test -covermode=atomic -coverprofile=coverage.txt ./...
      after_success: bash <(curl -s https://codecov.io/bash)
    - name: "build"
      before_install: skip
      install: skip
      before_script: skip
      script: go build ./kglbd/
