package control_plane

import (
	pb "dropbox/proto/kglb"
)

// State generated by Balancer to simlify access to required information since
// it provides set of pb.BalancerState's.
type BalancerState struct {
	// set of main BalancerState and fwmark states if it's enabled.
	States []*pb.BalancerState
	// rate of healthy upstreams.
	AliveRatio float32
	// the flag is false when Alive ratio of Balancer was positive, otherwise
	// false.
	InitialState bool
}
