name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    
    - name: Install protobuf compiler
      run: |
        mkdir ../protoc
        (
          set -e
          cd ../protoc
          wget "https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
          unzip "protoc-3.5.1-${TRAVIS_OS_NAME}-x86_64.zip"
        )
        export PATH="$(pwd)/../protoc/bin:$PATH"
        go install github.com/golang/protobuf/proto
        go install github.com/golang/protobuf/protoc-gen-go
    
    - name: Compile protobuf
      run: |
        cd ./proto
        protoc --go_out=. ./dropbox/proto/kglb/*.proto
        protoc --go_out=. ./dropbox/proto/kglb/healthchecker/*.proto

    - name: Build
      run: go build -v ./kglbd
